export const SUBMIT_AREA = 'SUBMIT_AREA';
export const TOGGLE_DEGREE = 'TOGGLE_DEGREE';
export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';

// export const TOGGLE_DEGREE = 'TOGGLE_DEGREE';